apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: db-credentials
spec:
  type: kv-v2
  mount: secret
  path: plg-test-namespace/demo-app/database
  refreshAfter: 30s
  destination:
    name: db-credentials
    create: true
  vaultAuthRef: default
